// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "EpicEnumsAndStructs.h"
#include "AC_InventoryItem.generated.h"


// Forward Declarations
struct FDataTabelRowHandle;
enum class EItemType : uint8;

UCLASS( ClassGroup=(Custom), meta=(BlueprintSpawnableComponent) )
class EPIC_INVENTORY_API UAC_InventoryItem : public UActorComponent
{
	GENERATED_BODY()

public:	
	// Sets default values for this component's properties
	UAC_InventoryItem();

	



	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Item Info")
	TArray<FStartingItems> ItemInformation;


protected:
	// Called when the game starts
	virtual void BeginPlay() override;

public:	
	// Called every frame
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

		
};
